### GET - /api
GET http://localhost:4000/api


### POST - /api/auth/signup
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "name": "Brijesh",
  "email":"brijesh@duck.com",
  "password": "12345678"
}


### POST - /api/auth/login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email":"brijesh@duck.com",
  "password": "12345678"
}


### POST - /api/auth/logout
POST http://localhost:4000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM4MDJkNzI4OTU2ZjIwZmRlNGQwYiIsImlhdCI6MTc2NzA4MDg0MiwiZXhwIjoxNzY3MDg0NDQyfQ.5wzLWY7IwU1tqvj8Qr5bFHtKq8BR9LMJGG8fnu16w1Q


### POST - /api/auth/refresh
POST http://localhost:4000/api/auth/refresh


### GET - /api/users/me
GET http://localhost:4000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM4YjkwNDYxMWYyNmQ2YWI2NTYyYSIsImlhdCI6MTc2NzA4MjkwMSwiZXhwIjoxNzY3MDg2NTAxfQ.y8jf11K60rCos6KZrBO9WIUushf4NCpF8ggU2KJIl4E


### POST - /api/apikeys
POST http://localhost:4000/api/apikeys
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzA4OTg1MywiZXhwIjoxNzY3MDkzNDUzfQ.xDCXr26upyPqiwEAX4-Au7KPbnd8A0XWZvibBwhYZ8k
Content-Type: application/json

{
  "name": "QuickTalk"
}


### GET - /api/apikeys
GET http://localhost:4000/api/apikeys
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzE2MjU4MSwiZXhwIjoxNzY3MTY2MTgxfQ.1E1PSXsT7mOXWWanCFyXtUzLV70RM-PE0PyJpb1VfUQ


### PATCH - /api/apikeys/:ID/disable
PATCH http://localhost:4000/api/apikeys/6953a875d3185b17fb84b8af/disable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzE2MjU4MSwiZXhwIjoxNzY3MTY2MTgxfQ.1E1PSXsT7mOXWWanCFyXtUzLV70RM-PE0PyJpb1VfUQ


### PATCH - /api/apikeys/:ID/enable
PATCH http://localhost:4000/api/apikeys/6953a875d3185b17fb84b8af/enable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzE2MjU4MSwiZXhwIjoxNzY3MTY2MTgxfQ.1E1PSXsT7mOXWWanCFyXtUzLV70RM-PE0PyJpb1VfUQ


### DELETE - /api/apikeys/:ID
DELETE http://localhost:4000/api/apikeys/6953a875d3185b17fb84b8af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzE2MjU4MSwiZXhwIjoxNzY3MTY2MTgxfQ.1E1PSXsT7mOXWWanCFyXtUzLV70RM-PE0PyJpb1VfUQ


### POST - /api/uploads/:ID/sign
POST http://localhost:4000/api/uploads/6953a7fd9645a38e4e4320e6/sign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTM5ODY4MDQ5OTMxZGViZDExMDZlZSIsImlhdCI6MTc2NzE2Njc0MywiZXhwIjoxNzY3MTcwMzQzfQ.7Byh_AcM7-0-tRh99fco8Ac_PMy129BM6VBQ7zprjx8
Content-Type: application/json

{
 "purpose": "avatar"
}


### POST - /api/uploads
POST http://localhost:4000/api/uploads
X-Upload-Token: upl_live_82d347d6d167c55dbf43429026b9b32366119948af51c1171ef343f0547ed129