@BASE_URL = http://localhost:4000/api


### GET - /
GET {{BASE_URL}}


### POST - /auth/register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "Jordan",
    "email": "jordan@ex.com",
    "password": "jordan1234"
}


### POST - /auth/login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "brijesh@ex.com",
    "password": "jordan1234"
}


### POST - /auth/logout
POST {{BASE_URL}}/auth/logout


### POST - /auth/refresh
POST {{BASE_URL}}/auth/refresh


### GET - /users/me
GET {{BASE_URL}}/users/me


### POST - /projects
POST {{BASE_URL}}/projects
Content-Type: application/json

{
    "name": "Cloudio"
}


### GET - /projects
GET {{BASE_URL}}/projects


### GET - /projects/:id
GET {{BASE_URL}}/projects/cmlem5sco0000txcprj3q7ehe


### PATCH - /projects/:id
PATCH {{BASE_URL}}/projects/cmlxo7ljk0000v4cp538kwal1
Content-Type: application/json

{
    "name": "SnapURL"
}


### PATCH - /projects/:id/revoke
PATCH {{BASE_URL}}/projects/cmlem5sco0000txcprj3q7ehe/revoke


### DELETE - /projects/:id
DELETE {{BASE_URL}}/projects/cmlxo7ljk0000v4cp538kwal1


### GET - /images
GET {{BASE_URL}}/images


### GET - /images/:id
GET {{BASE_URL}}/images/img_fe80877d0e33


### DELETE - /images/:id
DELETE {{BASE_URL}}/images/cmlxog75g000258cplhgel9ta